workers:
  -
    env: "production"
    shard_id: 0
    shard_num: 48
    log: "production_0_48"
  -
    env: "production"
    shard_id: 1
    shard_num: 48
    log: "production_1_48"
  -
    env: "production"
    shard_id: 2
    shard_num: 48
    log: "production_2_48"
  -
    env: "production"
    shard_id: 3
    shard_num: 48
    log: "production_3_48"
  -
    env: "production"
    shard_id: 4
    shard_num: 48
    log: "production_4_48"
  -
    env: "production"
    shard_id: 5
    shard_num: 48
    log: "production_5_48"
  -
    env: "production"
    shard_id: 6
    shard_num: 48
    log: "production_6_48"
  -
    env: "production"
    shard_id: 7
    shard_num: 48
    log: "production_7_48"
  -
    env: "production"
    shard_id: 8
    shard_num: 48
    log: "production_8_48"
  -
    env: "production"
    shard_id: 9
    shard_num: 48
    log: "production_9_48"
  -
    env: "production"
    shard_id: 10
    shard_num: 48
    log: "production_10_48"
  -
    env: "production"
    shard_id: 11
    shard_num: 48
    log: "production_11_48"
  -
    env: "production"
    shard_id: 12
    shard_num: 48
    log: "production_12_48"
  -
    env: "production"
    shard_id: 13
    shard_num: 48
    log: "production_13_48"
  -
    env: "production"
    shard_id: 14
    shard_num: 48
    log: "production_14_48"
  -
    env: "production"
    shard_id: 15
    shard_num: 48
    log: "production_15_48"
