workers:
  -
    env: "production"
    shard_id: 0
    shard_num: 48
    log: "production_0_48"
  -
    env: "production"
    shard_id: 1
    shard_num: 48
    log: "production_1_48"
  -
    env: "production"
    shard_id: 2
    shard_num: 48
    log: "production_2_48"
  -
    env: "production"
    shard_id: 3
    shard_num: 48
    log: "production_3_48"
  -
    env: "production"
    shard_id: 4
    shard_num: 48
    log: "production_4_48"
  -
    env: "production"
    shard_id: 5
    shard_num: 48
    log: "production_5_48"
  -
    env: "production"
    shard_id: 6
    shard_num: 48
    log: "production_6_48"
  -
    env: "production"
    shard_id: 7
    shard_num: 48
    log: "production_7_48"
  -
    env: "production"
    shard_id: 8
    shard_num: 48
    log: "production_8_48"
  -
    env: "production"
    shard_id: 9
    shard_num: 48
    log: "production_9_48"
  -
    env: "production"
    shard_id: 10
    shard_num: 48
    log: "production_10_48"
  -
    env: "production"
    shard_id: 11
    shard_num: 48
    log: "production_11_48"
  -
    env: "production"
    shard_id: 12
    shard_num: 48
    log: "production_12_48"
  -
    env: "production"
    shard_id: 13
    shard_num: 48
    log: "production_13_48"
  -
    env: "production"
    shard_id: 14
    shard_num: 48
    log: "production_14_48"
  -
    env: "production"
    shard_id: 15
    shard_num: 48
    log: "production_15_48"
  -
    env: "production"
    shard_id: 16
    shard_num: 48
    log: "production_16_48"
  -
    env: "production"
    shard_id: 17
    shard_num: 48
    log: "production_17_48"
  -
    env: "production"
    shard_id: 18
    shard_num: 48
    log: "production_18_48"
  -
    env: "production"
    shard_id: 19
    shard_num: 48
    log: "production_19_48"
  -
    env: "production"
    shard_id: 20
    shard_num: 48
    log: "production_20_48"
  -
    env: "production"
    shard_id: 21
    shard_num: 48
    log: "production_21_48"
  -
    env: "production"
    shard_id: 22
    shard_num: 48
    log: "production_22_48"
  -
    env: "production"
    shard_id: 23
    shard_num: 48
    log: "production_23_48"
  -
    env: "production"
    shard_id: 24
    shard_num: 48
    log: "production_24_48"
  -
    env: "production"
    shard_id: 25
    shard_num: 48
    log: "production_25_48"
  -
    env: "production"
    shard_id: 26
    shard_num: 48
    log: "production_26_48"
  -
    env: "production"
    shard_id: 27
    shard_num: 48
    log: "production_27_48"
  -
    env: "production"
    shard_id: 28
    shard_num: 48
    log: "production_28_48"
  -
    env: "production"
    shard_id: 29
    shard_num: 48
    log: "production_29_48"
  -
    env: "production"
    shard_id: 30
    shard_num: 48
    log: "production_30_48"
  -
    env: "production"
    shard_id: 31
    shard_num: 48
    log: "production_31_48"
  -
    env: "production"
    shard_id: 32
    shard_num: 48
    log: "production_32_48"
  -
    env: "production"
    shard_id: 33
    shard_num: 48
    log: "production_33_48"
  -
    env: "production"
    shard_id: 34
    shard_num: 48
    log: "production_34_48"
  -
    env: "production"
    shard_id: 35
    shard_num: 48
    log: "production_35_48"
  -
    env: "production"
    shard_id: 36
    shard_num: 48
    log: "production_36_48"
  -
    env: "production"
    shard_id: 37
    shard_num: 48
    log: "production_37_48"
  -
    env: "production"
    shard_id: 38
    shard_num: 48
    log: "production_38_48"
  -
    env: "production"
    shard_id: 39
    shard_num: 48
    log: "production_39_48"
  -
    env: "production"
    shard_id: 40
    shard_num: 48
    log: "production_40_48"
  -
    env: "production"
    shard_id: 41
    shard_num: 48
    log: "production_41_48"
  -
    env: "production"
    shard_id: 42
    shard_num: 48
    log: "production_42_48"
  -
    env: "production"
    shard_id: 43
    shard_num: 48
    log: "production_43_48"
  -
    env: "production"
    shard_id: 44
    shard_num: 48
    log: "production_44_48"
  -
    env: "production"
    shard_id: 45
    shard_num: 48
    log: "production_45_48"
  -
    env: "production"
    shard_id: 46
    shard_num: 48
    log: "production_46_48"
  -
    env: "production"
    shard_id: 47
    shard_num: 48
    log: "production_47_48"
