name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:1.0.0

    steps:
    - uses: actions/checkout@v2
    - name: Load secrets key
      run: echo '${{ secrets.TEST_SECRETS_KEY }}' > config/secrets/test.key
    - name: Install sudo package
      run: apt-get update && apt-get install sudo
    - name: Update packages list
      run: sudo apt-get update
    - name: Install dependencies
      run: shards install
    - name: Install packages
      run: sudo apt-get install -y libsodium-dev
    - name: Run format check
      run: make format
    - name: Run tests
      run: make spec
