name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Load secrets key
      run: echo '${{ secrets.TEST_SECRETS_KEY }}' > config/secrets/test.key
    - name: Install dependencies
      run: shards install
    - name: Run format check
      run: make format
    - name: Run tests
      run: make spec
